#!/bin/bash
# Minimal runner for Nginx in Docker
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LIB_DIR="${SCRIPT_DIR}/../../lib"

bash "${SCRIPT_DIR}/WEB01_check.sh"
bash "${SCRIPT_DIR}/WEB02_check.sh"
bash "${SCRIPT_DIR}/WEB03_check.sh"
bash "${SCRIPT_DIR}/WEB04_check.sh"
bash "${SCRIPT_DIR}/WEB05_check.sh"
bash "${SCRIPT_DIR}/WEB06_check.sh"
bash "${SCRIPT_DIR}/WEB07_check.sh"
bash "${SCRIPT_DIR}/WEB08_check.sh"
bash "${SCRIPT_DIR}/WEB09_check.sh"
bash "${SCRIPT_DIR}/WEB10_check.sh"
bash "${SCRIPT_DIR}/WEB11_check.sh"
bash "${SCRIPT_DIR}/WEB12_check.sh"
bash "${SCRIPT_DIR}/WEB13_check.sh"
bash "${SCRIPT_DIR}/WEB14_check.sh"
bash "${SCRIPT_DIR}/WEB15_check.sh"
bash "${SCRIPT_DIR}/WEB16_check.sh"
bash "${SCRIPT_DIR}/WEB17_check.sh"
bash "${SCRIPT_DIR}/WEB18_check.sh"
bash "${SCRIPT_DIR}/WEB19_check.sh"
bash "${SCRIPT_DIR}/WEB20_check.sh"
bash "${SCRIPT_DIR}/WEB21_check.sh"
bash "${SCRIPT_DIR}/WEB22_check.sh"
bash "${SCRIPT_DIR}/WEB23_check.sh"
bash "${SCRIPT_DIR}/WEB24_check.sh"
bash "${SCRIPT_DIR}/WEB25_check.sh"
bash "${SCRIPT_DIR}/WEB26_check.sh"

echo "Nginx Minimal Run Complete."